{{- if not .Values.global.secrets.useSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: secrets-{{ include "tyk-pro.fullname" . }}
  labels:
    app: secrets-data-{{ include "tyk-pro.fullname" . }}
    chart: {{ include "tyk-pro.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  redisPass: "{{ .Values.global.redis.pass }}"
  mongoURL: {{ include "tyk-pro.mongo_url" . | quote }}
  AdminSecret: "{{ .Values.global.secrets.AdminSecret }}"
  APISecret: "{{ .Values.global.secrets.APISecret }}"
  DashLicense: "{{ .Values.dashboard.license }}"
  MDCBLicense: "{{ .Values.mdcb.license }}"
  tibSecret: "{{ .Values.tib.secret }}"
{{- end }}
